name: Build & Publish Notebook Servers (TEMPLATE)
on:
  workflow_call:
    inputs:
      build_arch:
        required: true
        description: "architectures to build for, comma separated"
        type: string
      image_folders:
        required: true
        description: "image folders to build, ordered by dependency, whitespace separated"
        type: string

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ${{ vars.DOCKER_REGISTRY || 'docker.io/oneblockai' }}
  CACHE_IMAGE: ghcr.io/${{ github.repository }}/build-cache

jobs:
  build_and_push_images:
    name: Build & Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Notebook Server images
        env:
          ARCH: ${{ inputs.build_arch }}
          IMAGE_FOLDERS: ${{ inputs.image_folders }}
          SHOULD_TAG_LATEST: ${{ github.ref == 'refs/heads/main' }}
          SHOULD_TAG_VERSION: ${{ github.ref_type == 'tag' }}
          GIT_TAG: ${{ github.ref_name }}
        run: |
          if [[ "$SHOULD_TAG_LATEST" = "true" ]]; then
            export ALSO_TAG_LATEST=1
          fi
          if [[ "$SHOULD_TAG_VERSION" = "true" ]]; then
              export ALSO_TAG_VERSION=$(GIT_TAG)
          fi
          make docker-build-push-multi-arch